### ISSUE TITLE
How to keep a user session after page refresh?

### ISSUE THREAD

**Issue by goschevski** [guruahn/vue3-google-oauth2#1]
Hi,

How should I keep user session in case page is refreshed or user returned after 2 min for example (before expiration)?

Right now, I have login page with following code:

```
    async signIn () {
      const googleUser = await this.$gAuth.signIn();
      const authInfo = googleUser.getAuthResponse();
      const profile = googleUser.getBasicProfile();

      this.$store.commit('loginUser', {
        email: profile.getEmail(),
        name: profile.getName(),
        image: profile.getImageUrl()
      });

      this.$router.push({ name: 'home' });
    }
```

App will show login page when store's flag `isLoggedIn` is false.
Right now if user refresh the page, store is reset and login page will be show again.

I tried adding this to App.vue but it doesn't work

```
  beforeMount () {
    if (this.$gAuth.instance && this.$gAuth.instance.currentUser && this.$gAuth.instance.currentUser.get()) {
      const user = this.$gAuth.instance.currentUser.get();
      const profile = user.getBasicProfile();

      this.$store.commit('loginUser', {
        email: profile.getEmail(),
        name: profile.getName(),
        image: profile.getImageUrl()
      });

      this.$router.push({ name: 'home' });
    }
  },

```

**Comment by guruahn** [comment]
@goschevski 
we provide the reactivity state([Vue3GoogleOauth3](https://github.com/guruahn/vue3-google-oauth2#reactivity)).
Please refer to [the sample code](https://github.com/guruahn/vue3-google-oauth2-front-sample)(/src/components/HelloWorld.vue).
thanks

**Comment by goschevski** [comment]
Ah, sorry i missed that. I thought everything is under this.$gAuth. :)

Anyway, how to pull user data (name, email, etc.) without login (since it's logged in after refresh) ?

**Comment by guruahn** [comment]
you should watch `Vue3GoogleOauth3.isAuthorized`.
when `Vue3GoogleOauth3.isAuthorized` is changed to true, you can get user profile by `this.$gAuth.instance.currentUser.get()`

**Comment by goschevski** [comment]
Thanks.
