### ISSUE TITLE
Library uses deprecated Google signin API

### ISSUE THREAD

**Issue by moof2k** [guruahn/vue3-google-oauth2#13]
This application uses "https://apis.google.com/js/api.js" (index.js) which, according to https://developers.google.com/identity/sign-in/web/reference is discontinued as of Apr 30, 2022:

> We are [discontinuing the Google Sign-In JavaScript Platform Library for web](https://developers.googleblog.com/2021/08/gsi-jsweb-deprecation.html). Beginning April 30th, 2022 new web applications must use the Google Identity Services library, existing web apps may continue using the Platform Library until the March 31, 2023 deprecation date. For authentication and user sign-in, use the new Google Identity Services SDKs for both [Web](https://developers.google.com/identity/gsi/web) and [Android](https://developers.google.com/identity/one-tap/android) instead.

**Comment by Zeng95** [comment]
You can use this plugin [vue3-google-login](https://github.com/yobaji/vue3-google-login/) instead to have support for the new Google Identity Services JavaScript library.

**Comment by guruahn** [comment]
Thanks for your comments.
We will review and work on the change as soon as possible.
#16 same issue
