### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by hpx7** [guruahn/vue3-google-oauth2#2]
Do you have plans to add type declarations for this project? I'd like to use this in my typescript project with Vue 3

**Comment by florianrubel** [comment]
Yes please quick. I need it!

**Comment by reslear** [comment]
🙏

**Comment by guruahn** [comment]
@hpx7 Thanks for the comments. I'll make a plan sooner or later.

**Comment by jhordycg** [comment]
Hello, above I saw about __support for Typescript__, but I don't know if it's ready or if it's discarded.
