### ISSUE TITLE
Dynamically Set Scopes Prior To $gAuth.signIn

### ISSUE THREAD

**Issue by dalezak** [guruahn/vue3-google-oauth2#6]
Is there a way to dynamically set scopes prior to calling `this.$gAuth.signIn()`?

In different parts of our app we need different permissions. For example on sign in we only need `profile email openid`, but when importing Courses from Google Classroom we need `https://www.googleapis.com/auth/classroom.courses.readonly`.

I'd rather not request all permissions since not all users will use all this functionality, for example only Teachers can import courses and not Students. Is this possible?

**Comment by dalezak** [comment]
Would doing something like the following work to add additional scopes? Will this reinitialize the client?
```
this.$gAuth.load({
  scope: "profile email openid https://www.googleapis.com/auth/classroom.courses.readonly",
  prompt: "select_account"
});
const oauth = await this.$gAuth.signIn();
```

**Comment by guruahn** [comment]
지금은 불가능합니다만, 좋은 아이디어이네요. 새로운 범위로 로그인을 다시 하는 방법을 제공하는것을 고려해보겠습니다.
